---
name: CI

on:
  push:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  unit_tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: run tests
        run: python -m pytest --cov=. tests
      - name: run test coverage
        run: |
          coverage report
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_to_github:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: unit_tests
    steps:
      - uses: actions/checkout@v2
      - name: set up node # we need node for for semantic release
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.17
      - name: install semantic-release
        run: npm install @semantic-release/exec
      - name: run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
