name: Hello Actions!

on:
  push:
  pull_request:
    branches:
      - master
    types: [closed]

env:
  name: Devang C
jobs:
  push_only:
    runs-on: ubuntu-latest
    env:
      name: Devang
    steps:
      - name: Run a one-line script
        run: echo Hello, $name!

  pull_request_only:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: push_only
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project $name.
